[server]
enableXsrfProtection = true
enableCORS = false
preloadScript = "streamlit_sqlite_fix.py"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 